Issue 2: Add HEADER and NOTICE
pravega/presto-connector pull request #3
Opened 2021-03-05 07:52 UTC by fpj

* Adds a HEADER file containing the license header text. All files need to have the license header text at the top as is.
* Adds a NOTICE file, which is necessary for legal reasons.

Signed-off-by: Flavio Junqueira (fpj) <fpj@apache.org>

2021-03-05 13:54 UTC, derekm requested changes

2021-03-05 13:54 UTC, derekm commented on HEADER
> +Copyright 2021 Pravega Authors.
Year in notice file only.

2021-03-09 15:14 UTC, chipmaurer approved these changes

2021-03-09 15:28 UTC, derekm approved these changes

2021-03-09 15:34 UTC, merged